name: Build & Release

on:
  push:
    branches: [ main ]
    paths-ignore:
    - LICENSE
    - README.md
    - 'Config/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - LICENSE
    - README.md
    - 'Config/**'

jobs:
  setup:
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Generate Release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

  build:
    runs-on: ubuntu-latest
    needs: ["setup"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "no-tag")
          echo "CURRENT_TAG=$TAG" >> $GITHUB_ENV
          echo "CURRENT_TAG=$TAG" >> $GITHUB_OUTPUT
          echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate PPS Schemas
        run: |
          mkdir PermissionsSystem/pps
          git clone --depth 1 https://github.com/untrustedmodders/plugify-module-dotnet.git
          curl -o plugify-module-dotnet/generator/s2sdk.pplugin.in https://raw.githubusercontent.com/untrustedmodders/plugify-source-2/refs/heads/main/s2sdk.pplugin.in
          curl -o plugify-module-dotnet/generator/s2menu.pplugin.in https://raw.githubusercontent.com/untrustedmodders/plugify-menu_system/refs/heads/main/s2menu.pplugin.in
          python plugify-module-dotnet/generator/generator.py plugify-module-dotnet/generator/s2sdk.pplugin.in ./PermissionsSystem
          python plugify-module-dotnet/generator/generator.py plugify-module-dotnet/generator/s2menu.pplugin.in ./PermissionsSystem

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Setup Plugin Dir
        run: |
          mkdir Plugify
          mkdir Plugify/bin
          cp PermissionsSystem/bin/Release/net9.0/* Plugify/bin
          cp PermissionsSystem.pplugin Plugify/PermissionsSystem.pplugin
      
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: permissions_system_${{ env.GITHUB_SHA_SHORT }}
          path: Plugify

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: ["setup", "build"]
    if: ${{ needs.setup.outputs.release_created }}
    steps:
      - name: Prepare env
        shell: bash
        run: echo "GITHUB_SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: permissions_system_${{ env.GITHUB_SHA_SHORT }}
          path: build

      - name: Create zip archive
        run: |
          cd build
          zip -r permissions_system_${{ env.CURRENT_TAG }}_${{ env.GITHUB_SHA_SHORT }}.zip .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.setup.outputs.tag_name }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: build/permissions_system_${{ env.CURRENT_TAG }}_${{ env.GITHUB_SHA_SHORT }}.zip